name: Dev Build

on:
  push:
    branches: [main]
    paths-ignore:
      - CHANGELOG.md
      - '**.md'
      - LICENSE
      - '**/*.example.yml'
      - '**/*.example.yaml'

jobs:
  call-dev-build:
    uses: d0ugal/promexporter/.github/workflows/common/dev-build.yml@v1.14.0
    with:
      image_name: ${{ github.repository }}
    secrets: inherit
