name: Release Please

on:
  push:
    branches: [ main ]

jobs:
  call-release-please:
    uses: d0ugal/promexporter/.github/workflows/common/release-please.yml@v1.14.0
    with:
      image_name: ${{ github.repository }}
    secrets: inherit
